<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('users')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $timestamp = Carbon::now();

        DB::table('users')->insert([
            [
                'id' => 1,
                'nama' => 'Andi Saputra',
                'email' => 'andi@rs.com',
                'password' => Hash::make('andi123'),
                'role' => 'pegawai',
                'jurusan' => 'Keperawatan',
                'pendidikan_terakhir' => 'S1',
                'sertifikasi' => 1,
                'ikut_pelatihan' => 0,
                'umur' => 32,
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1992-04-15',
                'no_telepon' => '081234567891',
                'posisi' => 'Perawat IGD',
                'jabatan' => 'Staff Medis',
                'statusAkun' => 'Aktif',
                'b1' => 1,
                'b2' => 1,
                'b3' => 1,
                'b4' => 1,
                'b5' => 1,
                'a1' => 1,
                'a2' => 0,
                'a3' => 1,
                'a4' => 0,
                'a5' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ],
            [
                'id' => 2,
                'nama' => 'Budi Hartono',
                'email' => 'budi@rs.com',
                'password' => Hash::make('budi456'),
                'role' => 'atasan',
                'jurusan' => 'Farmasi',
                'pendidikan_terakhir' => 'D3',
                'sertifikasi' => 1,
                'ikut_pelatihan' => 1,
                'umur' => 29,
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1995-08-22',
                'no_telepon' => '082112345678',
                'posisi' => 'Apoteker',
                'jabatan' => 'Kepala Apotek',
                'statusAkun' => 'Aktif',
                'b1' => 1,
                'b2' => 1,
                'b3' => 1,
                'b4' => 1,
                'b5' => 1,
                'a1' => 0,
                'a2' => 0,
                'a3' => 0,
                'a4' => 0,
                'a5' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ],
            [
                'id' => 3,
                'nama' => 'Citra Lestari',
                'email' => 'citra@rs.com',
                'password' => Hash::make('citra789'),
                'role' => 'pegawai',
                'jurusan' => 'Kebidanan',
                'pendidikan_terakhir' => 'S1',
                'sertifikasi' => 1,
                'ikut_pelatihan' => 1,
                'umur' => 35,
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '1989-01-10',
                'no_telepon' => '081312345678',
                'posisi' => 'Bidan Rawat Inap',
                'jabatan' => 'Koordinator Bidan',
                'statusAkun' => 'Aktif',
                'b1' => 1,
                'b2' => 1,
                'b3' => 1,
                'b4' => 1,
                'b5' => 1,
                'a1' => 1,
                'a2' => 0,
                'a3' => 0,
                'a4' => 1,
                'a5' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ],
            [
                'id' => 4,
                'nama' => 'Dina Marwan',
                'email' => 'dina@rs.com',
                'password' => Hash::make('dina321'),
                'role' => 'pegawai',
                'jurusan' => 'Radiologi',
                'pendidikan_terakhir' => 'D3',
                'sertifikasi' => 1,
                'ikut_pelatihan' => 0,
                'umur' => 30,
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1994-09-30',
                'no_telepon' => '085212345678',
                'posisi' => 'Radiografer',
                'jabatan' => 'Ahli Radiologi',
                'statusAkun' => 'Aktif',
                'b1' => 1,
                'b2' => 1,
                'b3' => 1,
                'b4' => 1,
                'b5' => 1,
                'a1' => 1,
                'a2' => 0,
                'a3' => 0,
                'a4' => 1,
                'a5' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ],
            [
                'id' => 5,
                'nama' => 'Eko Susilo',
                'email' => 'eko@rs.com',
                'password' => Hash::make('eko654'),
                'role' => 'atasan',
                'jurusan' => 'Gizi',
                'pendidikan_terakhir' => 'S1',
                'sertifikasi' => 1,
                'ikut_pelatihan' => 1,
                'umur' => 40,
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1984-11-05',
                'no_telepon' => '087712345678',
                'posisi' => 'Ahli Gizi',
                'jabatan' => 'Kepala Departemen Gizi',
                'statusAkun' => 'Aktif',
                'b1' => 1,
                'b2' => 1,
                'b3' => 1,
                'b4' => 1,
                'b5' => 1,
                'a1' => 1,
                'a2' => 1,
                'a3' => 0,
                'a4' => 0,
                'a5' => 1,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ],
            [
                'id' => 6,
                'nama' => 'Yudha',
                'email' => '062140832917@student.polsri.ac.id',
                'password' => Hash::make('yudha123'),
                'role' => 'pegawai',
                'posisi' => 'Perawat ICU',
                'jabatan' => '',
                'jurusan' => '',
                'pendidikan_terakhir' => '',
                'tempat_lahir' => '',
                'tanggal_lahir' => null,
                'no_telepon' => '',
                'umur' => 0,
                'sertifikasi' => 1,
                'ikut_pelatihan' => 0,
                'statusAkun' => 'Aktif',
                'b1' => 1,
                'b2' => 1,
                'b3' => 1,
                'b4' => 1,
                'b5' => 1,
                'a1' => 1,
                'a2' => 1,
                'a3' => 1,
                'a4' => 1,
                'a5' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ],
            [
                'id' => 99,
                'nama' => 'Admin',
                'email' => 'admin@rs.com',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'posisi' => '',
                'jabatan' => '',
                'jurusan' => '',
                'pendidikan_terakhir' => '',
                'tempat_lahir' => '',
                'tanggal_lahir' => null,
                'no_telepon' => '',
                'umur' => 0,
                'sertifikasi' => 0,
                'ikut_pelatihan' => 0,
                'statusAkun' => 'Aktif',
                'b1' => 0,
                'b2' => 0,
                'b3' => 0,
                'b4' => 0,
                'b5' => 0,
                'a1' => 0,
                'a2' => 0,
                'a3' => 0,
                'a4' => 0,
                'a5' => 0,
                'created_at' => $timestamp,
                'updated_at' => $timestamp
            ]

        ]);
    }
}
